class McpSshError(Exception):
    """Base for all mcp-ssh errors. Always includes a human-readable message."""

class ServerNotFound(McpSshError): ...
class ServerAlreadyExists(McpSshError): ...
class ConnectionError(McpSshError): ...       # noqa: A001 (shadows builtin intentionally)
class AuthError(McpSshError): ...
class HostKeyError(McpSshError): ...
class SessionNotFound(McpSshError): ...
class SessionCapExceeded(McpSshError): ...
class ProcessNotFound(McpSshError): ...
class TmuxNotAvailable(McpSshError): ...
class RemoteCommandError(McpSshError):
    def __init__(self, msg: str, exit_code: int | None = None) -> None:
        super().__init__(msg)
        self.exit_code = exit_code
